<section class="builder-shell" data-builder>
    <header class="builder-head"><a href="/florist">← Florist</a><div><strong>Customise your bouquet</strong><span data-progress-label>1 of 12</span></div><a href="/selection">Selection</a></header>
    <div class="progress-track" aria-hidden="true"><i data-progress-bar></i></div>
    <form class="builder-form" data-builder-form novalidate>
        <div class="builder-stage">
            <section class="builder-step is-active" data-step="1"><p class="eyebrow">Begin with the moment</p><h1>What are the flowers for?</h1><p class="step-intro">Your occasion helps us understand the emotional tone without limiting the design.</p><div class="option-grid"><?php foreach($occasions as $item): ?><label class="option-card"><input type="radio" name="occasion_id" value="<?= (int)$item['id'] ?>" <?= (int)($draft['occasion_id']??0)===(int)$item['id']?'checked':'' ?> required><span><strong><?= e($item['name']) ?></strong><small><?= e($item['description']) ?></small></span></label><?php endforeach; ?></div></section>
            <section class="builder-step" data-step="2"><p class="eyebrow">Choose freely</p><h1>Which flowers are speaking to you?</h1><p class="step-intro">Select one or several. Your first choice is treated as the primary flower.</p><div class="chip-grid"><?php foreach($flowers as $item): ?><label class="choice-chip"><input type="checkbox" name="flower_ids[]" value="<?= (int)$item['id'] ?>" <?= in_array((int)$item['id'],$draft['flower_ids']??[],true)?'checked':'' ?>><span><?= e($item['name']) ?></span></label><?php endforeach; ?></div></section>
            <section class="builder-step" data-step="3"><p class="eyebrow">Closest inspiration</p><h1>These studies understand your flower mix.</h1><p class="step-intro">Ranking favours complete and exact combinations, then relevant partial matches. Choose one reference or leave it to our florist.</p><div class="match-status" data-match-status>Choose flowers to see ranked inspiration.</div><div class="match-grid" data-match-grid></div><label class="option-card option-card-wide"><input type="radio" name="sample_id" value="0" <?= empty($draft['sample_id'])?'checked':'' ?>><span><strong>Florist’s recommendation</strong><small>Use my choices without a fixed visual reference.</small></span></label></section>
            <section class="builder-step" data-step="4"><p class="eyebrow">Set the atmosphere</p><h1>What colours belong in the moment?</h1><p class="step-intro">Choose as many as feel right. Exact shades remain seasonal.</p><div class="colour-grid"><?php foreach($colours as $item): ?><label class="colour-card"><input type="checkbox" name="colour_ids[]" value="<?= (int)$item['id'] ?>" <?= in_array((int)$item['id'],$draft['colour_ids']??[],true)?'checked':'' ?>><i style="--swatch:<?= e($item['hex_value']??'#ddd') ?>"></i><span><?= e($item['name']) ?></span></label><?php endforeach; ?></div></section>
            <section class="builder-step" data-step="5"><p class="eyebrow">Shape the gesture</p><h1>How abundant should it feel?</h1><div class="option-grid"><?php foreach($sizes as $item): ?><label class="option-card"><input type="radio" name="size_id" value="<?= (int)$item['id'] ?>" <?= (int)($draft['size_id']??0)===(int)$item['id']?'checked':'' ?> required><span><strong><?= e($item['name']) ?></strong><small><?= e($item['description']) ?><?= (float)$item['price_adjustment']>0?' · +'.money($item['price_adjustment']):'' ?></small></span></label><?php endforeach; ?></div></section>
            <section class="builder-step" data-step="6"><p class="eyebrow">The finishing fold</p><h1>Choose one wrapping direction.</h1><div class="option-grid"><?php foreach($wrappings as $item): ?><label class="option-card"><input type="radio" name="wrapping_id" value="<?= (int)$item['id'] ?>" <?= (int)($draft['wrapping_id']??0)===(int)$item['id']?'checked':'' ?> required><span><strong><?= e($item['name']) ?></strong><small><?= e($item['description']) ?></small></span></label><?php endforeach; ?></div></section>
            <section class="builder-step" data-step="7"><p class="eyebrow">Optional details</p><h1>Add the small things that matter.</h1><div class="option-grid"><?php foreach($decorations as $item): ?><label class="option-card"><input type="checkbox" name="decoration_ids[]" value="<?= (int)$item['id'] ?>" <?= in_array((int)$item['id'],$draft['decoration_ids']??[],true)?'checked':'' ?>><span><strong><?= e($item['name']) ?></strong><small><?= e($item['description']) ?> · +<?= e(money($item['price_adjustment'])) ?></small></span></label><?php endforeach; ?></div></section>
            <section class="builder-step" data-step="8"><p class="eyebrow">A practical frame</p><h1>What budget should guide the design?</h1><div class="budget-grid"><label class="field"><span>Minimum budget (BND)</span><input type="number" name="budget_min" min="20" max="5000" step="1" value="<?= e($draft['budget_min']??60) ?>" required></label><label class="field"><span>Maximum budget (BND)</span><input type="number" name="budget_max" min="20" max="5000" step="1" value="<?= e($draft['budget_max']??120) ?>" required></label></div><p class="notice">This is a working range. Final price requires confirmation after flower availability and fulfilment are reviewed.</p></section>
            <section class="builder-step" data-step="9"><p class="eyebrow">Anything we should know?</p><h1>Leave room for the personal details.</h1><label class="field"><span>Additional instructions</span><textarea name="instructions" maxlength="2000" rows="7" placeholder="Recipient preferences, flowers to avoid, card wording, or the feeling you want to create"><?= e($draft['instructions']??'') ?></textarea><small><span data-character-count>0</span>/2000</small></label></section>
            <section class="builder-step" data-step="10"><p class="eyebrow">Customer and fulfilment</p><h1>How should we reach you?</h1><div class="form-grid"><label class="field"><span>Your name</span><input name="customer_name" autocomplete="name" maxlength="160" required></label><label class="field"><span>WhatsApp number</span><input name="customer_phone" type="tel" autocomplete="tel" maxlength="40" required></label><label class="field"><span>Email <small>optional</small></span><input name="customer_email" type="email" autocomplete="email"></label><label class="field"><span>Requested date</span><input name="requested_date" type="date" min="<?= date('Y-m-d') ?>" required></label><label class="field"><span>Preferred time</span><input name="requested_time" maxlength="50" placeholder="For example, 2–4 PM"></label><fieldset class="field field-full"><legend>Fulfilment</legend><div class="segmented"><label><input type="radio" name="fulfilment_method" value="pickup" checked><span>Pickup</span></label><label><input type="radio" name="fulfilment_method" value="delivery"><span>Delivery</span></label></div></fieldset><label class="field field-full" data-delivery-field hidden><span>Delivery address</span><textarea name="delivery_address" autocomplete="street-address"></textarea></label><label class="field field-full"><span>Customer notes <small>optional</small></span><textarea name="customer_notes" maxlength="2000"></textarea></label></div></section>
            <section class="builder-step" data-step="11"><p class="eyebrow">Review</p><h1>Your enquiry, at a glance.</h1><div class="review-card" data-review></div><p class="notice"><?= e($settings['florist_disclaimer']) ?></p></section>
            <section class="builder-step" data-step="12"><p class="eyebrow">Ready to send</p><h1>Save the enquiry, then continue in WhatsApp.</h1><div class="final-confirm"><p>We will save your selection with a unique CKF reference and prepare a structured message for <?= e($settings['business_name']) ?>.</p><label class="consent"><input type="checkbox" name="consent" value="1" required><span>I understand that sending this enquiry does not confirm an order. Availability, exact shades, fulfilment and final price require confirmation.</span></label><div class="form-errors" data-form-errors aria-live="assertive"></div></div></section>
        </div>
        <aside class="builder-summary"><p class="eyebrow">Your working brief</p><div data-live-summary><p>Selections will appear here as you build.</p></div><p class="summary-note">Your unfinished selection is kept in this browser session.</p></aside>
        <footer class="builder-actions"><button class="button button-outline" type="button" data-prev disabled>Back</button><button class="button" type="button" data-next>Continue</button><button class="button" type="submit" data-submit hidden>Save and open WhatsApp</button></footer>
    </form>
</section>

