<?php $errors=flash('errors')??[]; $old=flash('old')??[]; ?>
<header class="page-hero selection-hero"><p class="eyebrow">Selection summary</p><h1>Review the details before we talk.</h1><p>Nothing here is confirmed until our florist reviews availability, design, timing and price with you.</p></header>
<section class="selection-layout section-wrap">
    <div class="selection-items">
        <article class="selection-group"><div class="selection-group-head"><h2>Bouquet</h2><a href="/customise"><?= empty($selection['bouquet'])?'Start':'Edit' ?></a></div><?php if(!empty($selection['bouquet'])): ?><dl class="selection-dl"><div><dt>Selected flowers</dt><dd><?= count($selection['bouquet']['flower_ids']??[]) ?> chosen</dd></div><div><dt>Budget</dt><dd><?= e(money($selection['bouquet']['budget_min'])) ?>–<?= e(number_format((float)$selection['bouquet']['budget_max'],2)) ?></dd></div><div><dt>Instructions</dt><dd><?= e($selection['bouquet']['instructions']?:'None') ?></dd></div></dl><?php else: ?><div class="empty-state compact"><p>No bouquet has been added yet.</p></div><?php endif; ?></article>
        <article class="selection-group"><div class="selection-group-head"><h2>Café</h2><a href="/cafe">Add items</a></div><?php if(!empty($selection['cafe'])): ?><div class="selection-lines"><?php foreach($selection['cafe'] as $item): ?><div data-selection-line><div><strong><?= (int)$item['quantity'] ?> × <?= e($item['name']) ?></strong><span><?= e(implode(', ',$item['options'])) ?></span></div><span><?= e(money($item['unit_price']*$item['quantity'])) ?></span><button type="button" data-remove-cafe="<?= e($item['key']) ?>">Remove</button></div><?php endforeach; ?></div><?php else: ?><div class="empty-state compact"><p>No café items have been added.</p></div><?php endif; ?></article>
    </div>
    <form class="enquiry-form" action="/enquiries" method="post" novalidate><?= csrf_field() ?><h2>Customer and fulfilment</h2><?php if(isset($errors['selection'])): ?><p class="field-error"><?= e($errors['selection']) ?></p><?php endif; ?><div class="form-grid"><label class="field"><span>Your name</span><input name="customer_name" value="<?= e($old['customer_name']??'') ?>" autocomplete="name" required><?php if(isset($errors['customer_name'])):?><small class="field-error"><?= e($errors['customer_name']) ?></small><?php endif;?></label><label class="field"><span>WhatsApp number</span><input name="customer_phone" value="<?= e($old['customer_phone']??'') ?>" type="tel" autocomplete="tel" required><?php if(isset($errors['customer_phone'])):?><small class="field-error"><?= e($errors['customer_phone']) ?></small><?php endif;?></label><label class="field"><span>Email <small>optional</small></span><input name="customer_email" value="<?= e($old['customer_email']??'') ?>" type="email" autocomplete="email"></label><label class="field"><span>Requested date</span><input name="requested_date" type="date" min="<?= date('Y-m-d') ?>" value="<?= e($old['requested_date']??'') ?>" required></label><label class="field"><span>Preferred time</span><input name="requested_time" value="<?= e($old['requested_time']??'') ?>" placeholder="For example, 2–4 PM"></label><fieldset class="field field-full"><legend>Fulfilment</legend><div class="segmented"><label><input type="radio" name="fulfilment_method" value="pickup" <?= ($old['fulfilment_method']??'pickup')==='pickup'?'checked':'' ?>><span>Pickup</span></label><label><input type="radio" name="fulfilment_method" value="delivery" <?= ($old['fulfilment_method']??'')==='delivery'?'checked':'' ?>><span>Delivery</span></label></div></fieldset><label class="field field-full" data-delivery-field <?= ($old['fulfilment_method']??'pickup')==='delivery'?'':'hidden' ?>><span>Delivery address</span><textarea name="delivery_address"><?= e($old['delivery_address']??'') ?></textarea></label><label class="field field-full"><span>Customer notes</span><textarea name="customer_notes" maxlength="2000"><?= e($old['customer_notes']??'') ?></textarea></label></div><div class="notice"><strong>Before WhatsApp opens</strong><p>Your enquiry is validated and saved with a unique reference. This records that WhatsApp was opened; it does not mark anything as confirmed.</p></div><label class="consent"><input type="checkbox" name="consent" value="1" required><span>I understand this is an enquiry and final availability, shades, price and fulfilment require confirmation.</span></label><?php if(isset($errors['consent'])):?><small class="field-error"><?= e($errors['consent']) ?></small><?php endif;?><button class="button button-block" type="submit">Save enquiry and open WhatsApp</button></form>
</section>

